
width=512
height=512
noise_detail =  3 # brownian motion # of octaves
persistence = 2.1
lacunarity = 2
seed = 1
[dimensions]
# scene is assumed to be 1x1x1 by default

[physics]
gravity=9.8 # meters/second
[sunlight]
# up is North
