
width=256
height=256
# width=256
# height=256
# width=128
# height=128
noise_detail = 7 # brownian # of octaves
persistence = 2.1
lacunarity = 2
seed = 3
particles=10_000
[dimensions]

[physics]
gravity=9.8 # meters/second
[sunlight]
# up is North
